// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Tournamint_BackEnd.Database;

#nullable disable

namespace TournamintBackEnd.Migrations
{
    [DbContext(typeof(MatchContext))]
    partial class MatchContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("Tournamint_BackEnd.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerOne")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerOneScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PlayerTwo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PlayerTwoScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TournamentId")
                        .HasColumnType("INTEGER");

                    b.HasKey("MatchId");

                    b.ToTable("matches");
                });
#pragma warning restore 612, 618
        }
    }
}
